# Generated by Django 4.2.1 on 2023-05-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
