# Generated by Django 4.2.1 on 2023-06-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='business_sector',
            field=models.CharField(blank=True, choices=[('agriculture', 'Agriculture'), ('construction', 'Construction'), ('manufacturing', 'Manufacturing'), ('wholesale', 'Wholesale'), ('retail', 'Retail'), ('transportation', 'Transportation'), ('information', 'Information'), ('finance', 'Finance and Insurance'), ('healthcare', 'Healthcare'), ('education', 'Education Services')], max_length=100, null=True),
        ),
    ]
