# Generated by Django 4.2.1 on 2023-05-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0003_chatroom_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
