# Generated by Django 4.2.1 on 2023-05-24 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0010_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatrooms.file'),
        ),
    ]
