# Generated by Django 4.2.1 on 2023-05-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0011_chat_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='file',
        ),
    ]
