# Generated by Django 4.2.1 on 2023-05-25 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        ('chatrooms', '0012_remove_chat_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.poll'),
        ),
    ]
