# Generated by Django 4.2.1 on 2023-06-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0013_chat_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='groupchats/'),
        ),
    ]
